# 1.Creating arrays

## Instructions
Create a vector from the list [10, 20, 30].
Assign the result to the variable vector.
Create a matrix from the list of lists [[5, 10, 15], [20, 25, 30], [35, 40, 45]].
Assign the result to the variable matrix.

In [2]:
import numpy as np

vector = np.array([10, 20, 30])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

print(vector)
print(matrix)

[10 20 30]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


# 2.Array shape

## Instructions
Import numpy and assign to the alias np.
Assign the shape of vector to vector_shape.
Assign the shape of matrix to matrix_shape.
Display both vector_shape and matrix_shape using the print() function.

In [5]:
vector_shape = vector.shape
matrix_shape = matrix.shape
print(vector_shape)
print(matrix_shape)

(3,)
(3, 3)


# 3.Using NumPy

## Instructions
Use the numpy.genfromtxt() function to read "world_alcohol.csv" into a NumPy array named world_alcohol.
Use the type() and print() functions to display the type for world_alcohol.

In [15]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter=",")
print(type(world_alcohol))

<class 'numpy.ndarray'>


# 4. Data types

## Instructions
Assign the data type of world_alcohol to the variable world_alcohol_dtype.
Display world_alcohol_dtype using the print() function.

In [17]:
world_alcohol_dtype = world_alcohol.dtype
print(world_alcohol_dtype)

float64


# 6. Reading in the data correctly

## Instructions
When reading in world_alcohol.csv using numpy.genfromtxt():
Use the "U75" data type
Skip the first line in the dataset
Use the comma delimiter.
Assign the result to world_alcohol.
Use the print() function to display world_alcohol.

In [18]:
world_alcohol = np.genfromtxt('world_alcohol.csv', dtype="U75", skip_header=1, delimiter=",")
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


# 7. Indexing arrays

## Instructions
Assign the amount of alcohol Uruguayans drank in other beverages per capita in 1986 to uruguay_other_1986. This is the second row and fifth column.
Assign the country in the third row to third_country. Country is the third column.

In [29]:
uruguay_other_1986 = world_alcohol[1][4]
print(uruguay_other_1986)

0.5


In [22]:
third_country = world_alcohol[3]
print(third_country)

['1986' 'Americas' 'Colombia' 'Beer' '4.27']


# 8. Slicing arrays

## Instructions
Assign the whole third column from world_alcohol to the variable countries.
Assign the whole fifth column from world_alcohol to the variable alcohol_consumption.

In [35]:
countries = world_alcohol[:,2]
print(countries)

array(['Viet Nam', 'Uruguay', "Cte d'Ivoire", ..., 'Switzerland',
       'Papua New Guinea', 'Swaziland'], 
      dtype='<U75')

In [37]:
alcohol_consumption = world_alcohol[:,4]
print(alcohol_consumption)

['0' '0.5' '1.62' ..., '2.54' '0' '5.15']


# 9. Slicing one dimension

## Instructions
Assign all the rows and the first 2 columns of world_alcohol to first_two_columns.
Assign the first 10 rows and the first column of world_alcohol to first_ten_years.
Assign the first 10 rows and all of the columns of world_alcohol to first_ten_rows.

In [50]:
first_two_columns = world_alcohol[:,0:2]
first_two_columns

array([['1986', 'Western Pacific'],
       ['1986', 'Americas'],
       ['1985', 'Africa'],
       ..., 
       ['1986', 'Europe'],
       ['1987', 'Western Pacific'],
       ['1986', 'Africa']], 
      dtype='<U75')

In [51]:
first_ten_years = world_alcohol[0:9, 0]
first_ten_years

array(['1986', '1986', '1985', '1986', '1987', '1987', '1987', '1985',
       '1986'], 
      dtype='<U75')

In [52]:
first_ten_rows = world_alcohol[0:10, :]
first_ten_rows

array([['1986', 'Western Pacific', 'Viet Nam', 'Wine', '0'],
       ['1986', 'Americas', 'Uruguay', 'Other', '0.5'],
       ['1985', 'Africa', "Cte d'Ivoire", 'Wine', '1.62'],
       ['1986', 'Americas', 'Colombia', 'Beer', '4.27'],
       ['1987', 'Americas', 'Saint Kitts and Nevis', 'Beer', '1.98'],
       ['1987', 'Americas', 'Guatemala', 'Other', '0'],
       ['1987', 'Africa', 'Mauritius', 'Wine', '0.13'],
       ['1985', 'Africa', 'Angola', 'Spirits', '0.39'],
       ['1986', 'Americas', 'Antigua and Barbuda', 'Spirits', '1.55'],
       ['1984', 'Africa', 'Nigeria', 'Other', '6.1']], 
      dtype='<U75')

## 10. Slicing arrays

## Instructions
Assign the first 20 rows of the columns at index 1 and 2 of world_alcohol to first_twenty_regions.

In [58]:
first_twenty_regions = world_alcohol[0:20, 1:3]
first_twenty_regions

array([['Western Pacific', 'Viet Nam'],
       ['Americas', 'Uruguay'],
       ['Africa', "Cte d'Ivoire"],
       ['Americas', 'Colombia'],
       ['Americas', 'Saint Kitts and Nevis'],
       ['Americas', 'Guatemala'],
       ['Africa', 'Mauritius'],
       ['Africa', 'Angola'],
       ['Americas', 'Antigua and Barbuda'],
       ['Africa', 'Nigeria'],
       ['Africa', 'Botswana'],
       ['Americas', 'Guatemala'],
       ['Western Pacific', "Lao People's Democratic Republic"],
       ['Eastern Mediterranean', 'Afghanistan'],
       ['Western Pacific', 'Viet Nam'],
       ['Africa', 'Guinea-Bissau'],
       ['Americas', 'Costa Rica'],
       ['Africa', 'Seychelles'],
       ['Europe', 'Norway'],
       ['Africa', 'Kenya']], 
      dtype='<U75')