# 1. Systems Of Equations As Matrices
Instructions Multiply the first row of the matrix by 2.
Subtract the second row from the first row.
Subtract 3 times the first row from the second row.
Finally, divide the second row by 2 to get rid of the coefficient.
When you're finished, the first row should indicate that x
 equals 10
, and the second row should indicate that y
 equals 5
. We just solved our equation with matrices!
Hint
We can do mathematical operations on rows with NumPy. matrix[0] *= 2 multiplies the first row by 2.

In [1]:
import numpy as np

matrix = np.asarray([
        [2, 1, 25],
        [3, 2, 40]
    ], dtype=np.float32)

print(matrix)

matrix[0] *= 2
matrix[0] -= matrix[1]
matrix[1] -= (3 * matrix[0])
matrix[1] /= 2

print(matrix)

[[  2.   1.  25.]
 [  3.   2.  40.]]
[[  1.   0.  10.]
 [  0.   1.   5.]]


# 2. Solving More Complex Equations
Instructions
Solve for x
, y
, and z
 in matrix. When you're done, the matrix should look like this, but with the correct answers replacing the question marks
You can use print(matrix) to print the matrix out as you solve it and assess your progress.
Hint
To get started, subtract the first row from the third row.

In [2]:
matrix = np.array([
        [1, 2, 0, 7],
        [0, 3, 3, 11],
        [1, 2, 2, 11]
    ], dtype=np.float32)

print(matrix)

[[  1.   2.   0.   7.]
 [  0.   3.   3.  11.]
 [  1.   2.   2.  11.]]


In [3]:
matrix[2] -= matrix[0]
print(matrix)

[[  1.   2.   0.   7.]
 [  0.   3.   3.  11.]
 [  0.   0.   2.   4.]]


In [4]:
matrix[2] /= 2
print(matrix)

[[  1.   2.   0.   7.]
 [  0.   3.   3.  11.]
 [  0.   0.   1.   2.]]


In [5]:
matrix[1] -= (matrix[2] * 3)
print(matrix)

[[ 1.  2.  0.  7.]
 [ 0.  3.  0.  5.]
 [ 0.  0.  1.  2.]]


In [6]:
matrix[1] /= 3
print(matrix)

[[ 1.          2.          0.          7.        ]
 [ 0.          1.          0.          1.66666663]
 [ 0.          0.          1.          2.        ]]


In [7]:
matrix[0] -= matrix[1]
print(matrix)

[[ 1.          1.          0.          5.33333349]
 [ 0.          1.          0.          1.66666663]
 [ 0.          0.          1.          2.        ]]


# 3. Putting A Matrix Into Echelon Form
Instructions Swap rows to get matrix into echelon form.
matrix[[0,2]] = matrix[[2,0]] will exchange the first and third rows.
Hint
Remember that we subtract 1 from the row number to get the NumPy index for the row.

In [8]:
matrix = np.array([
        [0, 0, 0, 7],
        [0, 0, 1, 11],
        [1, 2, 2, 11],
        [0, 5, 5, 1]
    ], dtype=np.float32)

print(matrix)

[[  0.   0.   0.   7.]
 [  0.   0.   1.  11.]
 [  1.   2.   2.  11.]
 [  0.   5.   5.   1.]]


In [9]:
matrix[[0,2]] = matrix[[2,0]]
print(matrix)

[[  1.   2.   2.  11.]
 [  0.   0.   1.  11.]
 [  0.   0.   0.   7.]
 [  0.   5.   5.   1.]]


In [10]:
matrix[[1,3]] = matrix[[3,1]]
print(matrix)

[[  1.   2.   2.  11.]
 [  0.   5.   5.   1.]
 [  0.   0.   0.   7.]
 [  0.   0.   1.  11.]]


In [11]:
matrix[[2,3]] = matrix[[3,2]]
print(matrix)

[[  1.   2.   2.  11.]
 [  0.   5.   5.   1.]
 [  0.   0.   1.  11.]
 [  0.   0.   0.   7.]]


# 4. Reduced Row Echelon Form(Demo)

In [12]:
A = np.asarray([
        [0, 2, 1, 5],
        [1, 2, 1, 8],
        [3, 0, 1, 10],
        ], dtype=np.float32)

# First, we'll swap the second row with the first to get a non-zero coefficient in the first column
A[[0,1]] = A[[1,0]]

# The leading coefficient is already 1, so we don't need to divide
# Now, we need to make sure that our 1 coefficient is the only coefficient in its column
# We have to subtract 3 times the first row from the third row
A[2] -= 3 * A[0]

# Now, we move to row two
# We divide by 2 to get a 1 as the leading coefficient
A[1] /= 2

# We subtract 2 times the second row from the first to get rid of
# the second column coefficient in the first row
A[0] -= 2 * A[1]

# And we'll add 6 times the second row to the third to eliminate the leading coefficient there
A[2] += 6 * A[1]

# Now we can move to the third row where the leading coefficient is already 1
# We just need to subtract half of the third from the second
A[1] -= 0.5 * A[2]

# We've solved our system!
print(A)

[[ 1.  0.  0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]]


# 5. Inconsistent Systems Are Unsolvable
Instructions Find whether A is consistent by attempting to convert it to reduced row echelon form.
Assign True to A_consistent if it is, and False if it isn't.
Find whether B is consistent by attempting to convert it to reduced row echelon form.
Assign True to B_consistent if it is, and False if it isn't.
Hint
You can simplify A and B by trying to make it so that each variable has a 1 in a single row, and a 0 in every other row.

In [13]:
A = np.array([
        [10, 5, 20, 60],
        [3, 1, 0, 11],
        [8, 2, 2, 30],
        [0, 4, 5, 13]
    ], dtype=np.float32)

print(A)

[[ 10.   5.  20.  60.]
 [  3.   1.   0.  11.]
 [  8.   2.   2.  30.]
 [  0.   4.   5.  13.]]


In [14]:
A[0] /= 5

print(A)

[[  2.   1.   4.  12.]
 [  3.   1.   0.  11.]
 [  8.   2.   2.  30.]
 [  0.   4.   5.  13.]]


In [15]:
A[0] -= A[1]

print(A)

[[ -1.   0.   4.   1.]
 [  3.   1.   0.  11.]
 [  8.   2.   2.  30.]
 [  0.   4.   5.  13.]]


In [16]:
A[1] = (2*A[1])

print(A)

[[ -1.   0.   4.   1.]
 [  6.   2.   0.  22.]
 [  8.   2.   2.  30.]
 [  0.   4.   5.  13.]]


In [17]:
A[2] -= A[1]

print(A)

[[ -1.   0.   4.   1.]
 [  6.   2.   0.  22.]
 [  2.   0.   2.   8.]
 [  0.   4.   5.  13.]]


In [18]:
A[2] = (2*A[2])

print(A)

[[ -1.   0.   4.   1.]
 [  6.   2.   0.  22.]
 [  4.   0.   4.  16.]
 [  0.   4.   5.  13.]]


In [19]:
A[0] -= A[2]

print(A)

[[ -5.   0.   0. -15.]
 [  6.   2.   0.  22.]
 [  4.   0.   4.  16.]
 [  0.   4.   5.  13.]]


In [20]:
A[0] /= -5

print(A)

[[  1.  -0.  -0.   3.]
 [  6.   2.   0.  22.]
 [  4.   0.   4.  16.]
 [  0.   4.   5.  13.]]


In [21]:
A[2] /= 4

print(A)

[[  1.  -0.  -0.   3.]
 [  6.   2.   0.  22.]
 [  1.   0.   1.   4.]
 [  0.   4.   5.  13.]]


In [22]:
A[2] -= A[0]

print(A)

[[  1.  -0.  -0.   3.]
 [  6.   2.   0.  22.]
 [  0.   0.   1.   1.]
 [  0.   4.   5.  13.]]


In [23]:
A[1] /= 2

print(A)

[[  1.  -0.  -0.   3.]
 [  3.   1.   0.  11.]
 [  0.   0.   1.   1.]
 [  0.   4.   5.  13.]]


In [24]:
A[1] -= (3*A[0])

print(A)

[[  1.  -0.  -0.   3.]
 [  0.   1.   0.   2.]
 [  0.   0.   1.   1.]
 [  0.   4.   5.  13.]]


In [25]:
A[3] -= (4*A[1])

print(A)

[[ 1. -0. -0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  5.  5.]]


In [26]:
A[3] -= (5*A[2])

print(A)

[[ 1. -0. -0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


In [27]:
A[0] += A[1]

print(A)

[[ 1.  1.  0.  5.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


In [28]:
A[0] -= A[1]

print(A)

[[ 1.  0.  0.  3.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  0.]]


In [29]:
A_consistent = True

In [30]:
B = np.array([
        [5, -1, 3, 14],
        [0, 1, 2, 8],
        [0, -2, 5, 1],
        [0, 0, 6, 6]
    ], dtype=np.float32)

print(B)

[[  5.  -1.   3.  14.]
 [  0.   1.   2.   8.]
 [  0.  -2.   5.   1.]
 [  0.   0.   6.   6.]]


In [31]:
B[0] += B[1]

print(B)

[[  5.   0.   5.  22.]
 [  0.   1.   2.   8.]
 [  0.  -2.   5.   1.]
 [  0.   0.   6.   6.]]


In [32]:
B[0] /= 5

print(B)

[[ 1.         0.         1.         4.4000001]
 [ 0.         1.         2.         8.       ]
 [ 0.        -2.         5.         1.       ]
 [ 0.         0.         6.         6.       ]]


In [33]:
B[1] = (2*B[1])

print(B)

[[  1.          0.          1.          4.4000001]
 [  0.          2.          4.         16.       ]
 [  0.         -2.          5.          1.       ]
 [  0.          0.          6.          6.       ]]


In [34]:
B[2] += B[1]

print(B)

[[  1.          0.          1.          4.4000001]
 [  0.          2.          4.         16.       ]
 [  0.          0.          9.         17.       ]
 [  0.          0.          6.          6.       ]]


In [35]:
B[1] /= 2

print(B)

[[  1.          0.          1.          4.4000001]
 [  0.          1.          2.          8.       ]
 [  0.          0.          9.         17.       ]
 [  0.          0.          6.          6.       ]]


In [36]:
B[3] /= 6

print(B)

[[  1.          0.          1.          4.4000001]
 [  0.          1.          2.          8.       ]
 [  0.          0.          9.         17.       ]
 [  0.          0.          1.          1.       ]]


In [37]:
B[0] -= B[3]

print(B)

[[  1.          0.          0.          3.4000001]
 [  0.          1.          2.          8.       ]
 [  0.          0.          9.         17.       ]
 [  0.          0.          1.          1.       ]]


In [38]:
B[1] = (2*B[3])

print(B)

[[  1.          0.          0.          3.4000001]
 [  0.          0.          2.          2.       ]
 [  0.          0.          9.         17.       ]
 [  0.          0.          1.          1.       ]]


In [39]:
B_consistent = False

# 6. Complex Systems Can Have Infinite Solutions
Instructions
Check whether A has infinite solutions.
If it does, assign True to A_infinite.
If it doesn't, False to A_infinite.
Check whether B has infinite solutions.
If it does, assign True to B_infinite
If it doesn't, assign False to B_infinite.
Hint
You can simplify A and B by trying to make it so that each variable has a 1 in a single row, and a 0 in every other row.

In [86]:
A = np.array([
        [2, 4, 8, 20],
        [4, 8, 16, 40],
        [20, 5, 5, 10]
    ], dtype=np.float32)



In [87]:
A[0] /= 2
print(A)

[[  1.   2.   4.  10.]
 [  4.   8.  16.  40.]
 [ 20.   5.   5.  10.]]


In [88]:
A[1] /= 4
print(A)

[[  1.   2.   4.  10.]
 [  1.   2.   4.  10.]
 [ 20.   5.   5.  10.]]


In [89]:
A[2] /= 5
print(A)

[[  1.   2.   4.  10.]
 [  1.   2.   4.  10.]
 [  4.   1.   1.   2.]]


In [90]:
A[2] -= (4*A[0])
print(A)

[[  1.   2.   4.  10.]
 [  1.   2.   4.  10.]
 [  0.  -7. -15. -38.]]


In [91]:
A[1] -= A[0]
print(A)

[[  1.   2.   4.  10.]
 [  0.   0.   0.   0.]
 [  0.  -7. -15. -38.]]
