# 1. Introduction to Matrices 
Instructions Add vector1 and vector2, and assign the result to vector1_2.
Add vector3 and vector1, and assign the result to vector3_1.
Hint
You can add two vectors with the addition operator (+).

In [1]:
import numpy as np

vector1 = np.array([4, 5, 7, 10])
vector2 = np.array([8, 6, 3, 2])
vector3 = np.array([10, 4, 6, -1])

vector1_2 = vector1 + vector2
print(vector1_2)
vector3_1 = vector3 + vector1
print(vector3_1)

[12 11 10 12]
[14  9 13  9]


# 2. Multiplying Vectors By Scalars
Instructions
Multiply vector by the scalar 7 and assign the result to vector_7.
Divide vector by the scalar 8 and assign the result to vector_8.
Hint
Use the standard multiplication (*) and division (/) operators.




In [2]:
vector = np.array([4, -1, 7])

vector_7 = (7*vector)
print(vector_7)

vector_8 = (vector/8)
print((vector_8))

[28 -7 49]
[ 0.5   -0.125  0.875]


# 3. Plotting Vectors
Instructions
Make a new plot that contains the two vectors in the first plot, but also adds a vector that starts at origin 0,0, then goes over 4 and up 4.
This will end up at the coordinates 4,4.
The final plot will have three vectors on it.
Set the x and y-axis limits to [0,6].
Hint
Use plt.quiver([0,1,0], [0,2,0], [1,3,4], [2,2,4], angles='xy', scale_units='xy', scale=1) to make the plot.


In [3]:
import numpy as np
import matplotlib.pyplot as plt

X = [0, 1]
Y = [0, 2]
U = [1, 3]
V = [2, 2]

plt.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1)
plt.xlim([0, 6])
plt.ylim([0, 6])
plt.show()

plt.quiver([0,1,0], [0,2,0], [1,3,4], [2,2,4], angles='xy', scale_units='xy', scale=1)
plt.plot()

[]

# 4. Determining Vector Length
Instructions
Compute the length of the vector [23]
[
2	3 
]
, and assign the result to vector_length.
Hint
You can use the power operator (**) and 0.5 to find the square root of the sum of the vector's elements squared.

In [4]:
X = [0,2,0]
Y = [0,0,0]
U = [2,0,2]
V = [0,3,3]

plt.quiver(X,Y,U,V, angles='xy', scale_units='xy', scale=1)
plt.xlim([0,6])
plt.ylim([0,6])
plt.show()

vector_length = (2**2 + 3**2)**(1/2)
print(vector_length)

3.605551275463989


# 5. Calculating The Dot Product
Instructions
Assign the dot product of the vector [3,4,5,6], [5,6,7,8]
Hint
Multiply the elements at each position in both vectors, and add up the results.

In [7]:
dot = (3*5)+(4*6)+(5*7)+(6*8)
print(dot)

122


# 6. Making Predictions With Linear Regression
Instructions
For each row in nba:
Predict the pts column using the fga column.
Use the variables slope and intercept (which we already loaded in) to complete the linear regression equation.
Your final output should be a pandas series. Assign it to predictions.
Hint
You can calculate a prediction for the number of points with slope * nba["fga"] + intercept.

In [8]:
import pandas as pd
nba = pd.read_csv("nba.csv")
nba.head()

Name            Team  Number Position  Age Height  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25    6-2     180   
1    Jae Crowder  Boston Celtics      99       SF   25    6-6     235   
2   John Holland  Boston Celtics      30       SG   27    6-5     205   
3    R.J. Hunter  Boston Celtics      28       SG   22    6-5     185   
4  Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231   

             College   Salary  
0              Texas  7730337  
1          Marquette  6796117  
2  Boston University      NaN  
3      Georgia State  1148640  
4                NaN  5000000

In [16]:
slope = 1.26 
intercept = -18.92

predictions = slope * nba["Weight"] + intercept
predictions.head()

0    207.88
1    277.18
2    239.38
3    214.18
4    272.14
Name: Weight, dtype: float64

# 7. Multiplying A Matrix By A Vector
Instructions
Multiply nba_rows by nba_coefs.
nba_rows has two columns. The first contains the number of field goals each player attempted in 2013, and the second is a constant 1 value that enables us to add in the intercept.
Assign the result to predictions.
Hint
Remember to use np.dot.

In [22]:
import numpy as np

coefs = np.array([[3], [-1]])
rows = np.array([[2,1], [5,1], [-1,1]])

np.dot(rows, coefs)

predictions = np.dot(rows, coefs)
print(predictions)

[[ 5]
 [14]
 [-4]]


In [27]:
nba_coefs = np.array([[slope], [intercept]])
nba_rows = np.vstack([nba["Weight"], np.ones(nba.shape[0])]).T

predictions = np.dot(nba_rows, nba_coefs)
print(predictions)

[[ 207.88]
 [ 277.18]
 [ 239.38]
 [ 214.18]
 [ 272.14]
 [ 283.48]
 [ 277.18]
 [ 280.96]
 [ 220.48]
 [ 258.28]
 [ 308.68]
 [ 214.18]
 [ 258.28]
 [ 251.98]
 [ 299.86]
 [ 253.24]
 [ 220.48]
 [ 233.08]
 [ 258.28]
 [ 233.08]
 [ 243.16]
 [ 257.02]
 [ 201.58]
 [ 327.58]
 [ 233.08]
 [ 258.28]
 [ 279.7 ]
 [ 293.56]
 [ 239.38]
 [ 259.54]
 [ 245.68]
 [ 258.28]
 [ 239.38]
 [ 283.48]
 [ 233.08]
 [ 245.68]
 [ 233.08]
 [ 226.78]
 [ 302.38]
 [ 296.08]
 [ 283.48]
 [ 331.36]
 [ 277.18]
 [ 226.78]
 [ 283.48]
 [ 239.38]
 [ 301.12]
 [ 234.34]
 [ 251.98]
 [ 296.08]
 [ 245.68]
 [ 289.78]
 [ 293.56]
 [ 233.08]
 [ 233.08]
 [ 268.36]
 [ 327.58]
 [ 201.58]
 [ 239.38]
 [ 240.64]
 [ 258.28]
 [ 289.78]
 [ 239.38]
 [ 248.2 ]
 [ 258.28]
 [ 296.08]
 [ 220.48]
 [ 239.38]
 [ 258.28]
 [ 277.18]
 [ 251.98]
 [ 226.78]
 [ 283.48]
 [ 296.08]
 [ 302.38]
 [ 220.48]
 [ 225.52]
 [ 264.58]
 [ 308.68]
 [ 201.58]
 [ 220.48]
 [ 314.98]
 [ 270.88]
 [ 251.98]
 [ 223.  ]
 [ 258.28]
 [ 283.48]
 [ 258.28]
 [ 302.38]
 [ 251.98]
 [ 325.06]

In [29]:
A = np.array([[5,2], [3,5], [6,5]])
B = np.array([[3,1], [4,2]])

np.dot(A, B)

C =np.dot(A, B)

print(C)

[[23  9]
 [29 13]
 [38 16]]
